config/routes.rb
A2j::Application.routes.draw do
  resources :items
  root :to => "items#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :name, :release, :salesrank, :thumbnail_url, :album, :asin

  validates_presence_of :asin

  def self.lookup(id)
    res = Amazon::Ecs.item_lookup(id, :response_group => 'ItemAttributes,Images,EditorialReview,SalesRank')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.order("salesrank ASC")
    @chartitems = Item.where("salesrank <= ?", 100).order("release ASC")

    respond_to do |format|
      format.html
      format.json  { render :json => @items }
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create
    if params[:item][:asin].present? #make sure user submitted an ASIN
      asin = params[:item][:asin]
      az_connect #connect to Amazon
      res = Item.lookup(asin) #get our result

      if res.has_error?
        redirect_to new_item_path, :alert => "There was a problem with your entry.  Check the ASIN number and try again."
        return
      end

      res = res.items.first #call now intead of in model to preserve has_error? function
      @item.name = res.get('ItemAttributes/Artist').html_safe
      @item.album = res.get('ItemAttributes/Title').html_safe
      @item.thumbnail_url = res.get('MediumImage/URL')
      @item.release = res.get('ItemAttributes/ReleaseDate').html_safe
      @item.salesrank = res.get('SalesRank')
      @item.description = res.get('DetailPageURL')
      @item.asin = asin

      if @item.save!
        redirect_to @item, :notice => "Album #{@item.album} added to the database!  Thanks for keeping us up to date."
        return
      else
        redirect_to new_item_path, :alert => "There was a problem with your entry.  Check the ASIN number and try again."
      end
    else
      flash[:alert] = "Please enter a valid ASIN number."
      redirect_to new_item_path
    end
  end

  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html
      format.json  { render :json => @item }
    end
  end

end

private

def az_connect
  Amazon::Ecs.options = {
     :associate_tag => ENV["ASSOCIATE_TAG"],
     :AWS_access_key_id => ENV["KEY_ID"],
     :AWS_secret_key => ENV["SECRET_KEY"]
   }
end

app/helpers/application_helper.rb
module ApplicationHelper

  def items_as_json(items)
    items.collect do |item|
      {
        :name => item.name,
        :album => album.name,
        :salesrank => item.salesrank,
        :release => item.release
      }
    end.to_json
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/items/_new_item_form.html.erb
<h2>Add A New Album</h2>
<p>Simply paste an ASIN number for your favorite album into the form below to see how it ranks on the chart.</p>
<p class="muted">Visit <%= link_to "Amazon", "http://www.amazon.com/gp/bestsellers/music/?ie=UTF8&camp=1789&creative=390957&linkCode=ur2&tag=r0a90-20" %> to search for albums and their related ASIN ID numbers.</p>
<%= simple_form_for @item,:html => { :class => 'form-vertical' } do |f| %>
  <% if notification = f.error_notification %>
        <%= notification %>
    <% end %>
    <%= f.input :asin, :wrapper => :prepend, :label => false, required: true do %>
        <%= content_tag :span, "ASIN", :class => "add-on" %>
        <%= f.input_field :asin %>
    <% end %>
  <%= f.button :submit, value: "Add Album" %>
<% end %>

app/views/items/create.html.erb
<%= render 'items/new_item_form' %>

app/views/items/index.html.erb
<script>
$(document).ready(function() {
$('.thumbnail').tooltip();
});
</script>
<h1>Amazon Album Sales Rank Trends</h1>
<h3 class="muted">(Top 100 Displayed In Chart)
<%= content_tag :div, "", id: "amazon", data: {items: @chartitems} %>
<hr />
<ul class="thumbnails">
  <% @items.sort_by{|s| s[:salesrank]}.each do |item| %>
    <li class="span3">
      <div class="thumbnail indexitem">
        <%=link_to image_tag(item.thumbnail_url), item, class:"thumbnail", :rel => "tooltip", :title => item.name.html_safe %>
        <p class="text-info center"><strong><%= link_to item.name.html_safe, item %></strong></p>
        <p class="details text-info center"><%= link_to item.album.html_safe, item %></p>
        <p class="details text-info center">Sales Rank</p>
        <h2 class="rank center"><strong><%= item.salesrank %></strong></h2>
      </div>
    </li>
  <% end %>  
</ul>

app/views/items/new.html.erb
<%= render 'items/new_item_form' %>

app/views/items/show.html.erb
<script>
$(document).ready(function() {
$('.thumbnail').tooltip();
});
</script>
<div class="row">
  <div class="span5">
    <h2><%=@item.name.html_safe %></h2>
    <h3><%=@item.album.html_safe %></h2>
    <h5>Amazon Sales Rank: #<%= @item.salesrank %></h5>
    <p>Released on <%= @item.release %></p>
    <p>Purchase on <%= link_to "Amazon", @item.description %></p>
    <p><%= link_to "JSON", item_path(@item) + ".json" %>
  </div>
  <div class="span7">
    <img class="img-polaroid thumbnail" src="<%= @item.thumbnail_url%>" data-toggle="tooltip" title="<%= @item.album %>">
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "A2j", root_path, :class => 'brand' %>
<ul class="nav">
  <li>
    <%= link_to "Home", root_path %>
  </li>
  <li>
    <%= link_to "Add New Album", new_item_path %>
  </li>
  <li>
    <%= link_to "JSON Feed", "/items.json"%>
  </li>
<ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "A2j" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "A2j" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= yield :javascript_includes %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>